In [3]:
import numpy as np

In [11]:
def dft(x):
    x = np.asarray(x, dtype=float)
    print(x)
    N = x.shape[0]
    print(N)
    n = np.arange(N)
    print(n)
    k = n.reshape((N, 1))
    print(k*n)
    M = np.exp(-2j * np.pi * k * n / N)
    print(M)
    return np.dot(M, x)

In [15]:
y = [1,2,3,4,2,1,0,0]
dft(y)

[1. 2. 3. 4. 2. 1. 0. 0.]
8
[0 1 2 3 4 5 6 7]
[[ 0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7]
 [ 0  2  4  6  8 10 12 14]
 [ 0  3  6  9 12 15 18 21]
 [ 0  4  8 12 16 20 24 28]
 [ 0  5 10 15 20 25 30 35]
 [ 0  6 12 18 24 30 36 42]
 [ 0  7 14 21 28 35 42 49]]
[[ 1.00000000e+00+0.00000000e+00j  1.00000000e+00+0.00000000e+00j
   1.00000000e+00+0.00000000e+00j  1.00000000e+00+0.00000000e+00j
   1.00000000e+00+0.00000000e+00j  1.00000000e+00+0.00000000e+00j
   1.00000000e+00+0.00000000e+00j  1.00000000e+00+0.00000000e+00j]
 [ 1.00000000e+00+0.00000000e+00j  7.07106781e-01-7.07106781e-01j
   6.12323400e-17-1.00000000e+00j -7.07106781e-01-7.07106781e-01j
  -1.00000000e+00-1.22464680e-16j -7.07106781e-01+7.07106781e-01j
  -1.83697020e-16+1.00000000e+00j  7.07106781e-01+7.07106781e-01j]
 [ 1.00000000e+00+0.00000000e+00j  6.12323400e-17-1.00000000e+00j
  -1.00000000e+00-1.22464680e-16j -1.83697020e-16+1.00000000e+00j
   1.00000000e+00+2.44929360e-16j  3.06161700e-16-1.00000000e+00j
  -1.0000

array([ 1.30000000e+01+0.00000000e+00j, -3.12132034e+00-6.53553391e+00j,
       -1.37927510e-16+1.00000000e+00j,  1.12132034e+00-5.35533906e-01j,
       -1.00000000e+00-6.12323400e-16j,  1.12132034e+00+5.35533906e-01j,
       -9.18485099e-16-1.00000000e+00j, -3.12132034e+00+6.53553391e+00j])

In [ ]:
def dft(x):
    x = np.asarray(x, dtype=float)
    print(x)
    N = x.shape[0]
    print(N)
    n = np.arange(N)
    print(n)
    k = n.reshape((N, 1))
    print(k*n)
    M = np.exp(-2j * np.pi * k * n / N)
    print(M)
    return np.dot(M, x)

In [13]:
def fft(x):
    x = np.asarray(x, dtype=float)
    N = x.shape[0]
    if N % 2 > 0:
        raise ValueError("must be a power of 2")
    elif N <= 2:
        return dft(x)
    else:
        X_even = fft(x[::2])
        X_odd = fft(x[1::2])
        terms = np.exp(-2j * np.pi * np.arange(N) / N)
        return np.concatenate([X_even + terms[:int(N/2)] * X_odd,
                               X_even + terms[int(N/2):] * X_odd])

In [16]:
fft(y)

[1. 2.]
2
[0 1]
[[0 0]
 [0 1]]
[[ 1.+0.0000000e+00j  1.+0.0000000e+00j]
 [ 1.+0.0000000e+00j -1.-1.2246468e-16j]]
[3. 0.]
2
[0 1]
[[0 0]
 [0 1]]
[[ 1.+0.0000000e+00j  1.+0.0000000e+00j]
 [ 1.+0.0000000e+00j -1.-1.2246468e-16j]]
[2. 1.]
2
[0 1]
[[0 0]
 [0 1]]
[[ 1.+0.0000000e+00j  1.+0.0000000e+00j]
 [ 1.+0.0000000e+00j -1.-1.2246468e-16j]]
[4. 0.]
2
[0 1]
[[0 0]
 [0 1]]
[[ 1.+0.0000000e+00j  1.+0.0000000e+00j]
 [ 1.+0.0000000e+00j -1.-1.2246468e-16j]]


array([ 1.30000000e+01+0.00000000e+00j, -3.12132034e+00-6.53553391e+00j,
       -5.51091060e-16+1.00000000e+00j,  1.12132034e+00-5.35533906e-01j,
       -1.00000000e+00-8.57252759e-16j,  1.12132034e+00+5.35533906e-01j,
        6.73555740e-16-1.00000000e+00j, -3.12132034e+00+6.53553391e+00j])